server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/notobject/config-center.git
  profiles:
    active: @profiles.active@
eureka:
  instance:
    ip-address: @ip.address@
    instance-id: ${spring.application.name}:@ip.address@:${server.port}
    prefer-ip-address: true                      # 注册IP （缺省为主机名）
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30   # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    registry-fetch-interval-seconds: 15        # 拉取服务注册信息间隔（缺省为30s）
management:
  endpoints:
    web:
      exposure:
        include: '*'